### PR TITLE
86 fix linter

### PR DESCRIPTION
**Pull request by thomas-senechal**

### CODE REVIEW

**Comment by thomas-senechal** [comment]
I fixed every issues I could fix. There are only 5 issues left:
```
testnet/community-resources.rst:24: Line too long (19[5](https://github.com/massalabs/massa-docs/actions/runs/4007940801/jobs/6881464457#step:5:6)/120) (line-too-long)
testnet/community-resources.rst:2[6](https://github.com/massalabs/massa-docs/actions/runs/4007940801/jobs/6881464457#step:5:7): Line too long (535/120) (line-too-long)
testnet/community-resources.rst:[7](https://github.com/massalabs/massa-docs/actions/runs/4007940801/jobs/6881464457#step:5:8)5: Line too long (144/120) (line-too-long)
technical-doc/api.rst:31: Line too long (536/120) (line-too-long)
web3-dev/smart-contracts/playground.rst:34: Line too long (245/120) (line-too-long)
```

All of those are due to links. I will try to find a way to make the linter skip those errors.

**Comment by thomas-senechal** [comment]
Looks like there are no ways to tell `sphinx-lint` to ignore URLs or a specific line.

**Comment by qdrn** [comment]
Too bad :(. Do you mind fixing the conflicts and we'll merge as is for now ?

**Comment by thomas-senechal** [comment]
> Too bad 😢 . Do you mind fixing the conflicts and we'll merge as is for now ?

Okay ! Will work on it ASAP. 

For the links, I was thinking that we could use a tool to have shorter URLs ? It would also allow us to have some simpler and easier to read URLs. That includes the need of finding the right service and making sure we manage it well.

**Comment by qdrn** [comment]
> > Too bad 😢 . Do you mind fixing the conflicts and we'll merge as is for now ?
> 
> Okay ! Will work on it ASAP.
> 
> For the links, I was thinking that we could use a tool to have shorter URLs ? It would also allow us to have some simpler and easier to read URLs. That includes the need of finding the right service and making sure we manage it well.

I fear it adds another layer of complexity. Let's discuss that afterwards. Anyway it's not a priority. I thought it would be much easier...

**Review by qdrn — APPROVED** [review]

**Pull request merged**
