### PR TITLE
Add a linter.

### PR DESCRIPTION
**Pull request by thomas-senechal**

### CODE REVIEW

**Comment by thomas-senechal** [comment]
Hi @qdrn , I have a few questions for you:
- I decided to set the `max-line-length` value to 120. I think it's a nice compromise between the default value of 80 characters per line and letting people do whatever they want. What do you think about it ?
- I fixed all linter errors I saw expect for the `line-too-long` since it's a long task. I searched for a `.rst` formatter but couldn't find one. Do you want me to fix those errors ? Or should we merge that PR like that and create an issue to fix those issues ? 
- I noticed that we still have some warnings during `sphinx-build` command. Those issues are not raised by `sphinx-lint`. Do you want me to add a `sphinx-build` step in the linter to raise those warnings ?

**Comment by qdrn** [comment]
> Hi @qdrn , I have a few questions for you:
> 
> * I decided to set the `max-line-length` value to 120. I think it's a nice compromise between the default value of 80 characters per line and letting people do whatever they want. What do you think about it ?
> * I fixed all linter errors I saw expect for the `line-too-long` since it's a long task (approximatly 250 `line-too-long` errors to fix). I searched for a `.rst` formatter but couldn't find one. Do you want me to fix those errors ? Or should we merge that PR like that and create an issue to fix those issues ?
> * I noticed that we still have some warnings during `sphinx-build` command. Those issues are not raised by `sphinx-lint`. Do you want me to add a `sphinx-build` step in the linter to raise those warnings ?

- Sounds good to me. Except for people developing on their smartphone I think it makes more sense to use 120.
- Let's merge and fix afterwards if there are plenty of errors.
- What are those errors ? It's probably best to add this step so we avoid errors on the main branch!

**Comment by thomas-senechal** [comment]
> - Sounds good to me. Except for people developing on their smartphone I think it makes more sense to use 120.
> - Let's merge and fix afterwards if there are plenty of errors.
> - What are those errors ? It's probably best to add this step so we avoid errors on the main branch!

Okay for your 2 first points. 

For the third point, I will add a step in the CI to run `sphinx-build` and fail if there is a warning. I also noticed that Nathan fixed all the warnings we had during `sphinx-build`. 

You can see an example of the warnings we had in [that build](https://readthedocs.org/projects/massa/builds/18823745/), in the logs of the latest command. Or in the collapsed logs bellow.

<details>
  <summary>Another example</summary>

  ```sh
  reading sources... [100%] web3-dev/useful-resources
  /Users/thomas/massa/massa-docs/hackathon.rst:3: WARNING: Duplicate explicit target name: "here".
  /Users/thomas/massa/massa-docs/hackathon.rst:117: WARNING: Duplicate explicit target name: "here".
  /Users/thomas/massa/massa-docs/testnet/community-resources.rst:3: WARNING: Duplicate explicit target name: "telegram bot to track node activity".
  /Users/thomas/massa/massa-docs/web3-dev/decentralized-web.rst:7: WARNING: Duplicate explicit target name: "here".
  /Users/thomas/massa/massa-docs/web3-dev/massa-web3.rst:7: WARNING: Duplicate explicit target name: "thyra".
  /Users/thomas/massa/massa-docs/web3-dev/types.rst:7: WARNING: Duplicate explicit target name: "assemblyscript".
looking for now-outdated files... none found
  pickling environment... done
  checking consistency... /Users/thomas/massa/massa-docs/hackathon.rst: WARNING: document isn't included in any toctree
  /Users/thomas/massa/massa-docs/web3-dev/smart-contracts/Step_by_step.rst: WARNING: document isn't included in any toctree
  done
  ```
</details>

**Comment by qdrn** [comment]
Thanks for your answer. I also noticed that, for the same commit, sometimes I have warning and sometimes not. I'm probably missing something.

**Comment by qdrn** [comment]
> * rename [`Step_by_step.rst`](https://github.com/massalabs/massa-docs/blob/38c3d23bbb486c7d59aa6ba89c0a2d84cb91a1dc/web3-dev/smart-contracts/Step_by_step.rst) to `step_by_step.rst` for consistency with other files.

Yes!

> * add [`Step_by_step.rst`](https://github.com/massalabs/massa-docs/blob/38c3d23bbb486c7d59aa6ba89c0a2d84cb91a1dc/web3-dev/smart-contracts/Step_by_step.rst) to the `toctree` in [`web3-dev/smart-contracts.rst`](https://github.com/massalabs/massa-docs/tree/38c3d23bbb486c7d59aa6ba89c0a2d84cb91a1dc/web3-dev/smart-contracts.rst#massas-smart-contracts) to fix the error.

No, it's not ready yet. And now it's not even up to date. You can delete it for now. I think the latest version is in another branch anyway.

> I don't know what to do about [`hackthon.rst`](https://github.com/massalabs/massa-docs/blob/38c3d23bbb486c7d59aa6ba89c0a2d84cb91a1dc/hackathon.rst) tho. This file could be useful for a next hackathon so I think we should keep it. Maybe we should move it to the [`web3-dev`](https://github.com/massalabs/massa-docs/tree/38c3d23bbb486c7d59aa6ba89c0a2d84cb91a1dc/web3-dev) folder and so, add it to the `Web3 developers` `toctree` in [`index.rst`](https://github.com/massalabs/massa-docs/blob/38c3d23bbb486c7d59aa6ba89c0a2d84cb91a1dc/index.rst#contents) ?

Let's move this file to another branch so we can still update it when we need it. It's mostly relevant for hackathon's purposes. It should not be needed for people developing on Massa.

**Comment by thomas-senechal** [comment]
Everything is done. I will put that issue in review. 

Note that as Adrien [said](https://github.com/massalabs/massa-docs/pull/61#issuecomment-1339501181), we will merge this PR and fix the `line-too-long` errors later.

**Comment by qdrn** [comment]
As a followup we need to fix the lines too long error. I know it's not a funny one but I'd appreciate if someone volunteered for this one :)

**Pull request merged**
